### 1. Importando a biblioteca

Por convenção, importamos o NumPy utilizando o alias `np`

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
print(f'Versão do NumPy: {np.__version__}')

Versão do NumPy: 2.4.2


### 2. Criando Arrays (Vetores e Matrizes)

A principal estrutura de dados do NumPy é o `ndarray`

In [3]:
# Criando um array 1D (Vetor) a partir de uma lista
vetor = np.array([1, 2, 3, 4, 5])
print('Vetor 1D:', vetor)

# Criando um array 2D (Matriz) a partir de uma lista de listas
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print('\nMatriz 2D:\n', matriz)



Vetor 1D: [1 2 3 4 5]

Matriz 2D:
 [[1 2 3]
 [4 5 6]]


### Funções úteis para criação de Arrays

O NumPy possui funções nativas para gerar arrays comuns rapidamente, o que é muito útil para inicializar pesos em Redes Neurais, por exemplo

In [4]:
# Array de zeros
zeros = np.zeros((2, 3)) # 2 linhas, 3 colunas
print('Zeros:\n', zeros)

# Array de uns
uns = np.ones((3, 3))
print('\nUns:\n', uns)

# Array com uma sequência de números (similar ao range() do Python)
sequencia = np.arange(0, 10, 2)
print('\nSequência (arange):', sequencia) # início, fim (exclusivo), passo

# Valores linearmente espaçados
espacados = np.linspace(0, 1, 5) # 5 valores entre 0 e 1
print('\nLinspace:', espacados)

Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]

Uns:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Sequência (arange): [0 2 4 6 8]

Linspace: [0.   0.25 0.5  0.75 1.  ]


### 3. Inspecionando Arrays

É crucial saber o tamanho e o formato dos seus dados, especialmente ao preparar datasets para mineração de dados

In [5]:
print('Formato (shape):', matriz.shape) # (linhas, colunas)
print('Dimensões (ndim):', matriz.ndim) # número de dimensões
print('Tamanho Total (size):', matriz.size) # total de elementos
print('Tipo de dados (dtype):', matriz.dtype) # tipo dos elementos (ex: int64)

Formato (shape): (2, 3)
Dimensões (ndim): 2
Tamanho Total (size): 6
Tipo de dados (dtype): int64


### 4. Operações Matemáticas Básicas

O NumPy permite fazer operações elemento a elemento de forma direta, sem a necessidade de loops `for` (conceito conhecido como vetorização)

In [6]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print('Soma:', a + b)
print('Subtração:', a - b)
print('Multiplicação:', a * b)
print('Divisão:', a / b)

Soma: [11 22 33]
Subtração: [ -9 -18 -27]
Multiplicação: [10 40 90]
Divisão: [0.1 0.1 0.1]


In [7]:
# Funções estatísticas básicas
dados = np.array([15, 20, 25, 30, 35])
print('\nMédia:', np.mean(dados))
print('Desvio Padrão:', np.std(dados))
print('Valor Máximo:', np.max(dados))


Média: 25.0
Desvio Padrão: 7.0710678118654755
Valor Máximo: 35


### 5. Indexação e Fatiamento (Slicing)

Você pode acessar elementos específicos ou extrair subconjuntos do array

In [8]:
arr = np.array([10, 20, 30, 40, 50])

print('Primeiro elemento:', arr[0])
print('Último elemento:', arr[-1])
print('Fatiamento (índice 1 ao 3):', arr[1:4]) # o índice final é exclusivo

Primeiro elemento: 10
Último elemento: 50
Fatiamento (índice 1 ao 3): [20 30 40]


In [9]:
# Em matrizes 2D
matriz_ex = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print('\nMatriz completa:\n', matriz_ex)
print('\nElemento na linha 1, coluna 2:', matriz_ex[1, 2])
print('Todas as linhas, coluna 1:\n', matriz_ex[:, 1])


Matriz completa:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Elemento na linha 1, coluna 2: 60
Todas as linhas, coluna 1:
 [20 50 80]
